import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react'
import PageHeader from '../components/PageHeader'
import { api, jsonBody, money } from '../services/api'
import { toast } from '../services/toast'
import type { Account, Card, Category, ImportRule } from '../types'

type StatementRow = { id: string; date: string; description: string; amount: number; selected: boolean; kind: 'expense' | 'income'; categoryId?: number }

function numberFromText(value: string): number {
  const clean = value.replace(/R\$/gi, '').replace(/\s/g, '')
  if (clean.includes(',') && clean.includes('.')) return Number(clean.replace(/\./g, '').replace(',', '.'))
  if (clean.includes(',')) return Number(clean.replace(',', '.'))
  return Number(clean)
}
function normalizeDate(value: string): string {
  const raw = value.trim().replace(/['"]/g, '')
  const iso = raw.match(/^(\d{4})[-/]?(\d{2})[-/]?(\d{2})/); if (iso) return `${iso[1]}-${iso[2]}-${iso[3]}`
  const br = raw.match(/^(\d{2})[\/-](\d{2})[\/-](\d{4})/); if (br) return `${br[3]}-${br[2]}-${br[1]}`
  return new Date().toISOString().slice(0, 10)
}
function stableId(value: string): string { let hash = 2166136261; for (let i=0;i<value.length;i++){ hash ^= value.charCodeAt(i); hash = Math.imul(hash, 16777619) } return `stmt-${(hash>>>0).toString(16)}` }
function parseCsv(text: string): StatementRow[] {
  const lines = text.split(/\r?\n/).filter(Boolean); if (lines.length < 2) return []
  const separator = lines[0].includes(';') ? ';' : ','
  const headers = lines[0].split(separator).map(x => x.replace(/["']/g,'').trim().toLowerCase())
  const find = (...keys:string[]) => headers.findIndex(h => keys.some(k => h.includes(k)))
  const dateIndex = Math.max(0, find('data','date')); const descIndex = Math.max(1, find('descr','hist','memo','lançamento','lancamento','name')); let amountIndex = find('valor','amount','trnamt'); if (amountIndex < 0) amountIndex = headers.length - 1
  return lines.slice(1).map((line, index) => { const cols=line.split(separator).map(x=>x.replace(/^"|"$/g,'').trim()); const amount=numberFromText(cols[amountIndex]||'0'); const date=normalizeDate(cols[dateIndex]||''); const description=cols[descIndex]||`Movimentação ${index+1}`; return { id:stableId(`${date}|${description}|${amount}`), date, description, amount:Math.abs(amount), selected:true, kind:amount<0?'expense':'income' as const } }).filter(x=>Number.isFinite(x.amount)&&x.amount!==0)
}
function tag(block:string,name:string):string { const m=block.match(new RegExp(`<${name}>([^<\\r\\n]+)`,'i')); return m?.[1]?.trim()||'' }
function parseOfx(text:string):StatementRow[] { return text.split(/<STMTTRN>/i).slice(1).map((block,index)=>{const raw=numberFromText(tag(block,'TRNAMT')); const date=normalizeDate(tag(block,'DTPOSTED')); const description=tag(block,'MEMO')||tag(block,'NAME')||`Movimentação ${index+1}`; const fitid=tag(block,'FITID')||stableId(`${date}|${description}|${raw}`); return{id:`stmt-${fitid}`,date,description,amount:Math.abs(raw),selected:true,kind:raw<0?'expense':'income' as const}}).filter(x=>Number.isFinite(x.amount)&&x.amount!==0) }

export default function ImportPage(){
  const [rows,setRows]=useState<StatementRow[]>([]); const [accounts,setAccounts]=useState<Account[]>([]); const [cards,setCards]=useState<Card[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [rules,setRules]=useState<ImportRule[]>([]); const [accountId,setAccountId]=useState(''); const [cardId,setCardId]=useState(''); const [importing,setImporting]=useState(false); const [error,setError]=useState('')
  async function load(){const [a,c,k,r]=await Promise.all([api<Account[]>('/accounts'),api<Card[]>('/cards'),api<Category[]>('/categories'),api<ImportRule[]>('/import-rules')]);setAccounts(a);setCards(c);setCategories(k);setRules(r)}
  useEffect(()=>{void load()},[])
  const categoryName=useMemo(()=>new Map(categories.map(x=>[x.id,x.name])),[categories])
  async function chooseFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0]; if(!file)return; try{const text=await file.text(); let parsed=file.name.toLowerCase().endsWith('.ofx')||/<OFX/i.test(text)?parseOfx(text):parseCsv(text); parsed=parsed.map(row=>{const rule=rules.find(r=>r.kind===row.kind&&row.description.toLowerCase().includes(r.pattern.toLowerCase()));return{...row,categoryId:rule?.category_id}});setRows(parsed);setError(parsed.length?'':'Nenhuma movimentação reconhecida no arquivo.')}catch(err){setError(err instanceof Error?err.message:'Não foi possível ler o arquivo.')}finally{event.target.value=''}}
  async function importRows(){const selected=rows.filter(x=>x.selected); if(!selected.length)return; setImporting(true);let imported=0,skipped=0;try{for(const row of selected){try{if(row.kind==='expense'){const rule=rules.find(r=>r.kind==='expense'&&row.description.toLowerCase().includes(r.pattern.toLowerCase()));await api('/expenses',{method:'POST',...jsonBody({description:row.description,amount:row.amount,purchase_date:row.date,due_date:row.date,category_id:row.categoryId??rule?.category_id??null,expense_type:'variable',payment_method:cardId?'credit_card':rule?.payment_method||'transfer',merchant:row.description,notes:'Importado de extrato',status:'paid',paid_date:cardId?null:row.date,account_id:accountId?Number(accountId):null,card_id:cardId?Number(cardId):null,installments:1,auto_card_due:true,external_id:row.id})})}else{const rule=rules.find(r=>r.kind==='income'&&row.description.toLowerCase().includes(r.pattern.toLowerCase()));await api('/incomes',{method:'POST',...jsonBody({description:row.description,amount_expected:row.amount,amount_received:row.amount,expected_date:row.date,received_date:row.date,status:'received',account_id:accountId?Number(accountId):null,category_id:row.categoryId??rule?.category_id??null,notes:'Importado de extrato',external_id:row.id})})}imported++}catch{skipped++}}setRows([]);toast.success('Importação concluída',`${imported} movimentação(ões) importada(s)${skipped?` e ${skipped} ignorada(s)/duplicada(s)`:''}.`)}finally{setImporting(false)}}
  async function addRule(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await api('/import-rules',{method:'POST',...jsonBody({pattern:form.get('pattern'),kind:form.get('kind'),category_id:form.get('category_id')?Number(form.get('category_id')):null,payment_method:form.get('payment_method')||'pix'})});event.currentTarget.reset();await load();toast.success('Regra salva','Próximas importações usarão essa classificação automaticamente.')}
  async function removeRule(id:number){await api(`/import-rules/${id}`,{method:'DELETE'});await load()}
  return <><PageHeader title="Importar extrato" subtitle="CSV e OFX com reconhecimento de despesas, rendas e regras automáticas" actions={<label className="primary-button compact file-button">Selecionar CSV/OFX<input type="file" accept=".csv,.ofx,text/csv,application/x-ofx" onChange={chooseFile}/></label>}/>{error&&<div className="form-error">{error}</div>}
  <section className="panel statement-settings"><h3>Destino da importação</h3><div className="inline-finance-form"><select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Sem conta vinculada</option>{accounts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={cardId} onChange={e=>setCardId(e.target.value)}><option value="">Não é fatura de cartão</option>{cards.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{rows.length>0&&<button className="primary-button" disabled={importing} onClick={importRows}>{importing?'Importando...':`Importar ${rows.filter(x=>x.selected).length} selecionada(s)`}</button>}</div><small>Se um cartão for selecionado, o Smart Finance calcula automaticamente a fatura pelo fechamento e vencimento do cartão.</small></section>
  {rows.length>0&&<section className="panel"><h3>Pré-visualização</h3><div className="statement-list">{rows.map((row,index)=><label key={`${row.id}-${index}`}><input type="checkbox" checked={row.selected} onChange={e=>setRows(current=>current.map((x,i)=>i===index?{...x,selected:e.target.checked}:x))}/><span><strong>{row.description}</strong><small>{row.date.split('-').reverse().join('/')} • {row.kind==='expense'?'Despesa':'Renda'} {row.categoryId?`• ${categoryName.get(row.categoryId)||''}`:''}</small></span><b className={row.kind==='expense'?'negative-text':'positive-text'}>{money(row.amount)}</b></label>)}</div></section>}
  <section className="panel"><h3>Regras automáticas</h3><p>Exemplo: texto “POSTO” → categoria Combustível. A regra será aplicada nas próximas importações.</p><form className="import-rule-form" onSubmit={addRule}><input name="pattern" required placeholder="Texto contido na descrição"/><select name="kind"><option value="expense">Despesa</option><option value="income">Renda</option></select><select name="category_id"><option value="">Sem categoria</option>{categories.filter(x=>x.is_active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="payment_method"><option value="pix">Pix</option><option value="debit">Débito</option><option value="transfer">Transferência</option><option value="boleto">Boleto</option></select><button className="secondary-button">Adicionar regra</button></form><div className="rule-list">{rules.map(rule=><div key={rule.id}><span><strong>Contém “{rule.pattern}”</strong><small>{rule.kind==='expense'?'Despesa':'Renda'} • {rule.category_id?categoryName.get(rule.category_id)||'Categoria':'Sem categoria'}</small></span><button className="danger-text" onClick={()=>removeRule(rule.id)}>Excluir</button></div>)}</div></section></>
}
